// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0pM0v37f664O6vkXyYCqBP7vojgV7f5E',
    appId: '1:380605215705:web:582b7e93eaee7db016dfc8',
    messagingSenderId: '380605215705',
    projectId: 'cal-ai-clone-e57ea',
    authDomain: 'cal-ai-clone-e57ea.firebaseapp.com',
    storageBucket: 'cal-ai-clone-e57ea.firebasestorage.app',
    measurementId: 'G-PE6LB2N3V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSkXA-ZNdcuxPUOqhDvuS2W0gvLeZ-DvM',
    appId: '1:380605215705:android:798e914cd007de4a16dfc8',
    messagingSenderId: '380605215705',
    projectId: 'cal-ai-clone-e57ea',
    storageBucket: 'cal-ai-clone-e57ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQEq8wdvSr6NjlCQpJMqDrYInKG8BbVJE',
    appId: '1:380605215705:ios:29813503c1877aa816dfc8',
    messagingSenderId: '380605215705',
    projectId: 'cal-ai-clone-e57ea',
    storageBucket: 'cal-ai-clone-e57ea.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQEq8wdvSr6NjlCQpJMqDrYInKG8BbVJE',
    appId: '1:380605215705:ios:29813503c1877aa816dfc8',
    messagingSenderId: '380605215705',
    projectId: 'cal-ai-clone-e57ea',
    storageBucket: 'cal-ai-clone-e57ea.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0pM0v37f664O6vkXyYCqBP7vojgV7f5E',
    appId: '1:380605215705:web:eb259f1b18cf81d416dfc8',
    messagingSenderId: '380605215705',
    projectId: 'cal-ai-clone-e57ea',
    authDomain: 'cal-ai-clone-e57ea.firebaseapp.com',
    storageBucket: 'cal-ai-clone-e57ea.firebasestorage.app',
    measurementId: 'G-EX3QM6BSV8',
  );
}
